return {
	corape = {
		activatewhenbuilt = true,
		blocking = false,
		buildpic = "CORAPE.DDS",
		buildtime = 18000,
		canfly = true,
		canmanualfire = true,
		canmove = true,
		collide = true,
		collisionvolumeoffsets = "0 5 3",
		collisionvolumescales = "48 18 48",
		collisionvolumetype = "CylY",
		cruisealtitude = 100,
		energycost = 6800,
		explodeas = "mediumexplosiongeneric",
		footprintx = 3,
		footprintz = 3,
		health = 1560,
		hoverattack = true,
		maxacc = 0.2,
		maxdec = 0.2,
		maxslope = 10,
		maxwaterdepth = 0,
		metalcost = 370,
		nochasecategory = "VTOL",
		objectname = "Units/CORAPE.s3o",
		script = "Units/corape_lus.lua",
		seismicsignature = 0,
		selfdestructas = "mediumExplosionGenericSelfd",
		sightdistance = 550,
		speed = 159,
		turninplaceanglelimit = 360,
		turnrate = 600,
		customparams = {
			maxrange = "410",
			model_author = "Flaka",
			normaltex = "unittextures/cor_normal.dds",
			subfolder = "CorAircraft/T2",
			techlevel = 2,
			unitgroup = "weapon",
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "vtolcrmv",
			},
			select = {
				[1] = "vtolcrac",
			},
		},
		weapondefs = {
			vtol_rocket = {
				areaofeffect = 128,
				avoidfeature = false,
				burnblow = true,
				castshadow = true,
				cegtag = "missiletrailsmall-simple",
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0.15,
				explosiongenerator = "custom:genericshellexplosion-medium",
				firestarter = 70,
				flighttime = 2,
				impulsefactor = 0.123,
				model = "cormissile2fast.s3o",
				name = "Heavy a2g shrapnel rockets",
				noselfdamage = true,
				predictboost = 0.2,
				range = 410,
				reloadtime = 1.1,
				smokecolor = 0.55,
				smokeperiod = 7,
				smokesize = 9,
				smoketime = 14,
				smoketrail = true,
				smoketrailcastshadow = false,
				soundhit = "rockhit",
				soundhitwet = "splsmed",
				soundstart = "rocklit3",
				soundtrigger = true,
				startvelocity = 300,
				texture1 = "null",
				texture2 = "smoketrailbar",
				tolerance = 8000,
				tracks = true,
				turnrate = 9000,
				turret = false,
				weaponacceleration = 200,
				weapontimer = 5,
				weapontype = "MissileLauncher",
				weaponvelocity = 700,
				damage = {
					default = 122,
					subs = 61,
					vtol = 15,
				},
			},
			exp_heavyrocket = {
				areaofeffect = 64,
				avoidfeature = false,
				burst = 4,
				burstrate = 0.1,
				cegtag = "missiletrailsmall-red",
				commandfire = true,
				craterboost = 0,
				cratermult = 0,
				dance = 44,
				edgeeffectiveness = 0.65,
				explosiongenerator = "custom:genericshellexplosion-catapult",
				firestarter = 70,
				flighttime = 3.2,
				impulsefactor = 0.6,
				metalpershot = 0,
				model = "catapultmissile.s3o",
				movingaccuracy = 1200,
				name = "Light manual a2g rocket barrage",
				noselfdamage = true,
				proximitypriority = -1,
				range = 710,
				reloadtime = 30,
				smokecolor = 0.5,
				smokeperiod = 4,
				smokesize = 8.5,
				smoketime = 16,
				smoketrail = true,
				smoketrailcastshadow = false,
				soundhit = "rockhit",
				soundhitwet = "splsmed",
				soundstart = "rapidrocket3",
				startvelocity = 360,
				texture1 = "null",
				texture2 = "smoketrailbar",
				tolerance = 3000,
				trajectoryheight = 0.18,
				turnrate = 0,
				turret = true,
				weaponacceleration = 100,
				weapontimer = 6,
				weapontype = "MissileLauncher",
				weaponvelocity = 630,
				wobble = 3900,
				customparams = {
					overrange_distance = 840,
					projectile_destruction_method = "descend",
				},
				damage = {
					default = 450,
				},
			},
		},
		weapons = {
			[1] = {
				badtargetcategory = "VTOL",
				def = "VTOL_ROCKET",
				onlytargetcategory = "SURFACE",
			},
			[2] = {
				badtargetcategory = "VTOL GROUNDSCOUT",
				def = "EXP_HEAVYROCKET",
				maindir = "0 0 1",
				maxangledif = 45,
				onlytargetcategory = "SURFACE",
			},
		},
	},
}
