return {
	paradrop_parachute = {
		blocking = false,
		canattack = false,
		canmove = false,
		capturable = false,
		category = "OBJECT",
		collisionvolumeoffsets = "0 0 0",
		collisionvolumescales = "0.1 0.1 0.1",
		collisionvolumetype = "CylY",
		crushresistance = 2500,
		footprintx = 1,
		footprintz = 1,
		health = 5600000,
		hidedamage = true,
		mass = 0,
		maxslope = 64,
		maxwaterdepth = 1000,
		objectname = "Units/paradrop_parachute.dae",
		reclaimable = false,
		repairable = false,
		script = "Units/paradrop_parachute.cob",
		seismicsignature = 0,
		sightdistance = 0,
		sonarstealth = true,
		stealth = true,
		upright = false,
		sfxtypes = {
			explosiongenerators = {
				[1] = "custom:paradrop-blue-trail-short",
				[2] = "custom:paradrop-blue-trail-medium",
				[3] = "custom:paradrop-blue-trail-long",
			},
		},
		customparams = {
			decoration = 2,
			nohealthbars = true,
			normaltex = "unittextures/blank_normal.dds",
			subfolder = "other",
		},
	},
}
