return {
	armblade = {
		blocking = false,
		buildpic = "ARMBLADE.DDS",
		buildtime = 32000,
		canfly = true,
		canmove = true,
		collide = true,
		cruisealtitude = 110,
		energycost = 22000,
		explodeas = "mediumExplosionGeneric",
		footprintx = 2,
		footprintz = 2,
		health = 3000,
		hoverattack = true,
		idleautoheal = 5,
		idletime = 1800,
		maxacc = 0.6,
		maxdec = 0.35,
		maxslope = 10,
		maxwaterdepth = 0,
		metalcost = 1250,
		nochasecategory = "VTOL",
		objectname = "Units/ARMBLADE.s3o",
		script = "Units/ARMBLADE.cob",
		seismicsignature = 0,
		selfdestructas = "mediumExplosionGenericSelfd",
		sightdistance = 720,
		speed = 224,
		turninplaceanglelimit = 360,
		turnrate = 720,
		customparams = {
			model_author = "FireStorm",
			normaltex = "unittextures/Arm_normal.dds",
			subfolder = "ArmAircraft/T2",
			techlevel = 2,
			unitgroup = "weapon",
		},
		sfxtypes = {
			crashexplosiongenerators = {
				[1] = "crashing-small",
				[2] = "crashing-small",
				[3] = "crashing-small2",
				[4] = "crashing-small3",
				[5] = "crashing-small3",
			},
			pieceexplosiongenerators = {
				[1] = "airdeathceg3",
				[2] = "airdeathceg4",
				[3] = "airdeathceg2",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "vtolarmv",
			},
			select = {
				[1] = "vtolarac",
			},
		},
		weapondefs = {
			vtol_sabot = {
				alphadecay = 0.08,
				areaofeffect = 24,
				avoidfeature = false,
				burst = 2,
				burstrate = 0.15,
				burnblow = true,
				cegtag = "impulse-trail",
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0.25,
				explosiongenerator = "custom:genericshellexplosion-medium-bomb",
				impulsefactor = 0.33,
				name = "Pop-up heavy g2g gauss cannon",
				nogap = false,
				noselfdamage = true,
				range = 700,
				reloadtime = 5.5,
				separation = 1.0,
				sizedecay = 0.06,
				soundhit = "xplomed2",
				soundhitwet = "splshbig",
				soundstart = "mavgun5",
				soundstartvolume = 42,
				stages = 14,
				targetmoveerror = 0.2,
				tolerance = 6000,
				turret = false,
				weapontype = "Cannon",
				weaponvelocity = 1500,
				damage = {
					default = 480,
					vtol = 150,
				},
			},
		},
		weapons = {
			[1] = {
				def = "VTOL_SABOT",
				onlytargetcategory = "SURFACE",
			},
		},
	},
}