return {
	armbrawl = {
		blocking = false,
		buildpic = "ARMBRAWL.DDS",
		buildtime = 13500,
		canfly = true,
		canmove = true,
		collide = true,
		cruisealtitude = 100,
		energycost = 6200,
		explodeas = "mediumExplosionGeneric",
		footprintx = 3,
		footprintz = 3,
		health = 1780,
		hoverattack = true,
		idleautoheal = 5,
		idletime = 1800,
		maxacc = 0.24,
		maxdec = 0.44,
		maxslope = 10,
		maxwaterdepth = 0,
		metalcost = 310,
		nochasecategory = "VTOL",
		objectname = "Units/ARMBRAWL.s3o",
		script = "Units/ARMBRAWL.cob",
		seismicsignature = 0,
		selfdestructas = "mediumExplosionGenericSelfd",
		sightdistance = 640,
		speed = 160.8,
		turninplaceanglelimit = 360,
		turnrate = 800,
		customparams = {
			firingceg = "barrelshot-tiny",
			model_author = "FireStorm",
			normaltex = "unittextures/Arm_normal.dds",
			subfolder = "ArmAircraft/T2",
			techlevel = 2,
			unitgroup = "weapon",
		},
		sfxtypes = {
			crashexplosiongenerators = {
				[1] = "crashing-small",
				[2] = "crashing-small",
				[3] = "crashing-small2",
				[4] = "crashing-small3",
				[5] = "crashing-small3",
			},
			explosiongenerators = {
				[1] = "custom:barrelshot-tiny",
			},
			pieceexplosiongenerators = {
				[1] = "airdeathceg3",
				[2] = "airdeathceg4",
				[3] = "airdeathceg2",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "vtolarmv",
			},
			select = {
				[1] = "vtolarac",
			},
		},
		weapondefs = {
			vtol_emg =  {
				areaofeffect = 8,
				avoidfeature = false,
				beamttl = 1,
				burst = 10,
				burstrate = 0.03333,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				duration = 1,
				edgeeffectiveness = 0.15,
				energypershot = 5,
				explosiongenerator = "custom:genericshellexplosion-medium-lightning2",
				firestarter = 50,
				impactonly = 1,
				impulsefactor = 0,
				intensity = 24,
				laserflaresize = 5,
				name = "Close-quarters lightning turret",
				noselfdamage = true,
				range = 540,
				reloadtime = 1.4,
				rgbcolor = "0.5 0.5 1",
				soundhit = "lashit",
				soundhitwet = "sizzle",
				soundstart = "lghthvy1",
				soundtrigger = true,
				soundstartvolume = 28,
				thickness = 2,
				turret = true,
				weapontype = "LightningCannon",
				weaponvelocity = 400,
				customparams = {
					noattackrangearc = 1,
					spark_ceg = "genericshellexplosion-splash-lightning",
					spark_forkdamage = "0.5",
					spark_maxunits = "3",
					spark_range = "110",
				},
				damage = {
					default = 35,
					subs = 10,
				},
			},
		},
		weapons = {
			[1] = {
				def = "VTOL_EMG",
				onlytargetcategory = "NOTSUB",
			},
		},
	},
}
