return {
	armlance = {
		buildpic = "ARMLANCE.DDS",
		buildtime = 19000,
		canfly = true,
		canmove = true,
		collide = true,
		cruisealtitude = 90,
		energycost = 8000,
		explodeas = "mediumExplosionGeneric",
		footprintx = 4,
		footprintz = 4,
		health = 1920,
		maxacc = 0.1325,
		maxaileron = 0.01384,
		maxbank = 0.8,
		maxdec = 0.075,
		maxelevator = 0.01009,
		maxpitch = 0.625,
		maxrudder = 0.00559,
		maxslope = 10,
		maxwaterdepth = 0,
		metalcost = 400,
		nochasecategory = "VTOL",
		objectname = "Units/ARMLANCE.s3o",
		radardistance = 800,
		script = "Units/ARMLANCE_lus.lua",
		seismicsignature = 0,
		selfdestructas = "mediumExplosionGenericSelfd",
		sightdistance = 500,
		sonardistance = 800,
		speed = 285,
		speedtofront = 0.06417,
		turnradius = 64,
		usesmoothmesh = true,
		wingangle = 0.06259,
		wingdrag = 0.185,
		customparams = {
			model_author = "Flaka",
			normaltex = "unittextures/Arm_normal.dds",
			subfolder = "ArmAircraft/T2",
			techlevel = 2,
			unitgroup = "sub",
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "vtolarmv",
			},
			select = {
				[1] = "vtolarac",
			},
		},
		weapondefs = {
			armair_torpedo = {
				areaofeffect = 16,
				avoidfeature = false,
				avoidfriendly = false,
				burnblow = true,
				burst = 3,
				burstrate = 0.3,
				cegtag = "torpedotrail-small",
				collidefriendly = false,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0.15,
				explosiongenerator = "custom:genericshellexplosion-large-uw",
				flighttime = 4,
				impulsefactor = 0.123,
				model = "cortorpedo.s3o",
				mygravity = 0.1,
				name = "Light homing torpedo launcher",
				noselfdamage = true,
				range = 400,
				reloadtime = 6,
				soundhit = "xplodep3",
				soundhitvolume = 3.5,
				soundhitwet = "splsmed",
				soundhitwetvolume = 14,
				soundstart = "bombrel",
				startvelocity = 35,
				tolerance = 2000,
				tracks = true,
				turnrate = 20000,
				turret = false,
				waterweapon = true,
				weaponacceleration = 35,
				weapontimer = 6,
				weapontype = "TorpedoLauncher",
				weaponvelocity = 200,
				customparams = {
					norangering = 1,
					speceffect = "torpwaterpen",
				},
				damage = {
					default = 375,
				},
			},
			vtol_sabot = {
				areaofeffect = 32,
				avoidfeature = false,
				burst = 3,
				burstrate = 0.08,
				burnblow = true,
				castshadow = true,
				cegtag = "missiletrailsmall-simple",
				collidefriendly = false,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0.15,
				explosiongenerator = "custom:genericshellexplosion-medium",
				firestarter = 70,
				impulsefactor = 0.123,
				model = "cormissile2.s3o",
				name = "Heavy a2g armor-piercing sabot missile launcher",
				noselfdamage = true,
				range = 800,
				reloadtime = 2.26667,
				stockpile = true,
				stockpiletime = 15,
				smokecolor = 0.55,
				smokeperiod = 6,
				smokesize = 9,
				smoketime = 12,
				smoketrail = true,
				smoketrailcastshadow = false,
				soundhit = "SabotHit",
				soundhitwet = "splshbig",
				soundstart = "SabotFire",
				soundtrigger = true,
				sprayangle = 2200,
				startvelocity = 350,
				texture1 = "null",
				texture2 = "smoketrailbar",
				tolerance = 8000,
				tracks = true,
				turnrate = 6000,
				turret = false,
				weaponacceleration = 120,
				weapontimer = 2,
				weapontype = "MissileLauncher",
				weaponvelocity = 550,
				customparams = {
					stockpilelimit = 3,
				},
				damage = {
					default = 190,
				},
			},
		},
		weapons = {
			[1] = {
				def = "ARMAIR_TORPEDO",
				onlytargetcategory = "SHIP SUB",
			},
			[2] = {
				def = "VTOL_SABOT",
				onlytargetcategory = "SURFACE",
			},
		},
	},
}
