return {
	armkam = {
		blocking = false,
		buildpic = "ARMKAM.DDS",
		buildtime = 5050,
		canfly = true,
		canmove = true,
		collide = true,
		cruisealtitude = 70,
		energycost = 2300,
		explodeas = "smallExplosionGeneric",
		footprintx = 2,
		footprintz = 2,
		health = 560,
		hoverattack = true,
		idleautoheal = 5,
		idletime = 1800,
		maxacc = 0.35,
		maxdec = 0.375,
		maxslope = 10,
		maxwaterdepth = 0,
		metalcost = 135,
		nochasecategory = "VTOL",
		objectname = "Units/ARMKAM.s3o",
		script = "Units/ARMKAM.cob",
		seismicsignature = 0,
		selfdestructas = "smallExplosionGenericSelfd",
		sightdistance = 500,
		speed = 194.8,
		turninplaceanglelimit = 360,
		turnrate = 1400,
		customparams = {
			model_author = "FireStorm",
			normaltex = "unittextures/Arm_normal.dds",
			subfolder = "ArmAircraft",
			unitgroup = "weapon",
		},
		sfxtypes = {
			crashexplosiongenerators = {
				[1] = "crashing-small",
				[2] = "crashing-small",
				[3] = "crashing-small2",
				[4] = "crashing-small3",
				[5] = "crashing-small3",
			},
			explosiongenerators = {
				[1] = "custom:barrelshot-tiny",
			},
			pieceexplosiongenerators = {
				[1] = "airdeathceg2",
				[2] = "airdeathceg3",
				[3] = "airdeathceg4",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "vtolarmv",
			},
			select = {
				[1] = "vtolarac",
			},
		},
		weapondefs = {
			emg = {
				alphadecay = 0.08,
				areaofeffect = 64,
				avoidfeature = false,
				burnblow = true,
				cegtag = "impulse-trail",			
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0.015,
				explosiongenerator = "custom:genericshellexplosion-small-bomb",
				impulsefactor = 3.33,
				impulseboost  = 2.4,
				name = "Pop-up heavy g2g gauss cannon",
				nogap = false,
				noselfdamage = true,
				range = 400,
				reloadtime = 2.5,
				separation = 1.0,
				sizedecay = 0.06,
				soundhit = "xplomed1",
				soundhitwet = "splshmed",
				soundstart = "mavgun4",
				soundstartvolume = 24,
				stages = 14,
				targetmoveerror = 0.2,
				tolerance = 6000,
				turret = false,
				weapontype = "LaserCannon",
				weaponvelocity = 900,
				damage = {
					default = 106,
					vtol = 15,
				},
			},
		},
		weapons = {
			[1] = {
				--badtargetcategory = "VTOL",
				def = "EMG",
				onlytargetcategory = "NOTSUB",
			},
		},
	},
}
