return {
	cormando = {
		activatewhenbuilt = true,
		autoheal = 10,
		builddistance = 275,
		builder = true,
		buildpic = "CORMANDO.DDS",
		buildtime = 7200,
		canassist = true,
		canguard = false,
		cancapture = true,
		canmove = true,
		canreclaim = true,
		canrepair = true,
		canrestore = false,
		capturespeed = 600,
		collisionvolumeoffsets = "0 0 0",
		collisionvolumescales = "38 50 22",
		collisionvolumetype = "box",
		energycost = 5000,
		energystorage = 20,
		explodeas = "mediumexplosiongeneric",
		footprintx = 2,
		footprintz = 2,
		health = 1500,
		mass = 750,
		maxacc = 0.4025,
		maxdec = 1.725,
		maxslope = 20,
		metalcost = 410,
		movementclass = "ABOT3",
		nochasecategory = "VTOL",
		objectname = "Units/CORMANDO.s3o",
		radardistance = 900,
		radardistancejam = 150,
		reclaimspeed = 80,
		repairspeed = 80,
		script = "Units/CORMANDO.cob",
		seismicsignature = 4,
		selfdestructas = "mediumExplosionGenericSelfd",
		sightdistance = 600,
		speed = 72,
		turninplace = true,
		turninplaceanglelimit = 90,
		turninplacespeedlimit = 1.65,
		turnrate = 1168.40002,
		upright = true,
		workertime = 200,
		buildoptions = {
			[1] = "corvalk",
			[2] = "corfink",
			[3] = "cormine1",
			[4] = "cormine2",
			[5] = "cordrag",
		},
		customparams = {
			fall_damage_multiplier = 0,
			mine_resistant = true,
			model_author = "FireStorm",
			normaltex = "unittextures/cor_normal.dds",
			paralyzemultiplier = 0.2,
			paratrooper = true,
			reaimtime = 2,
			self_only_assist = true,
			stealths_transport = true,
			subfolder = "CorBots/T2",
			techlevel = 2,
			unitgroup = "buildert2",
			water_fall_damage_multiplier = 0,
		},
		sfxtypes = {
			explosiongenerators = {
				[1] = "custom:barrelshot-small",
				[2] = "custom:radarpulse_t1",
			},
		},
		sounds = {
			build = "nanlath2",
			canceldestruct = "cancel2",
			capture = "capture2",
			repair = "repair2",
			underattack = "warning1",
			working = "reclaim1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "kbcormov",
			},
			select = {
				[1] = "kbcorsel",
			},
		},
		weapondefs = {
			commando_blaster = {
				areaofeffect = 8,
				avoidfeature = false,
				beamdecay = 0.5,
				beamtime = 0.2,
				beamttl = 1,
				collidefriendly = false,
				corethickness = 0.2,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				duration = 0.01,
				edgeeffectiveness = 0.15,
				energypershot = 300,
				explosiongenerator = "custom:laserhit-emp",
				impactonly = 1,
				impulsefactor = 0,
				laserflaresize = 6,
				name = "Close-quarters EMP laser",
				noselfdamage = true,
				paralyzer = true,
				paralyzetime = 6,
				range = 260,
				reloadtime = 2.5,
				rgbcolor = "0.7 0.7 1",
				soundhitdry = "",
				soundhitwet = "sizzle",
				soundstart = "hackshot",
				soundtrigger = 1,
				thickness = 1.2,
				turret = true,
				weapontype = "BeamLaser",
				weaponvelocity = 800,
				damage = {
					default = 600,
					vtol = 160,
				},
			},
		},
		weapons = {
			[1] = {
				badtargetcategory = "VTOL",
				def = "COMMANDO_BLASTER",
				fastautoretargeting = true,
				fastquerypointupdate = true,
				onlytargetcategory = "EMPABLE",
			},
		},
	},
}
