return {
	legmrv = {
		activatewhenbuilt = true,
		maxacc = 0.09,
		maxdec = 0.14,
		energycost = 5000,
		metalcost = 410,
		builddistance = 275,
		builder = true,
		buildpic = "LEGMRV.DDS",
		buildtime = 7200,
		canassist = true,
		canguard = false,
		cancapture = true,
		canmove = true,
		canreclaim = false,
		canrepair = true,
		canrestore = false,
		capturespeed = 600,
		collisionvolumeoffsets = "0 -6 0",
		collisionvolumescales = "34 26 38",
		collisionvolumetype = "CylZ",
		corpse = "DEAD",
		explodeas = "largeexplosiongeneric",
		footprintx = 2,
		footprintz = 2,
		leavetracks = true,
		health = 1500,
		maxslope = 12,
		repairspeed = 80,
		speed = 86.4,
		maxwaterdepth = 100,
		movementclass = "TANK2",
		nochasecategory = "VTOL",
		objectname = "Units/LEGMRV.s3o",
		script = "Units/LEGMRV_clean.cob",
		seismicsignature = 0,
		selfdestructas = "largeExplosionGenericSelfd",
		sightdistance = 500,
		trackoffset = 0,
		trackstrength = 6,
		tracktype = "corwidetracks",
		trackwidth = 30,
		turninplace = true,
		turninplaceanglelimit = 90,
		turninplacespeedlimit = 1.72656,
		turnrate = 600,
		workertime = 180,
		buildoptions = {
			[1] = "leglts",
			[2] = "legscout",
			[3] = "legmine1",
			[4] = "legmine2",
			[5] = "legdrag",
			[6] = "legrl",
		},
		customparams = {
			basename = "base",
			fall_damage_multiplier = 0,
			firingceg = "barrelshot-tiny",
			kickback = "-2.4",
			mine_resistant = true,
			model_author = "ZephyrSkies",
			normaltex = "unittextures/leg_normal.dds",
			paralyzemultiplier = 0,
			paratrooper = true,
			reaimtime = 2,
			self_only_assist = true,
			stealths_transport = true,
			subfolder = "CorVehicles/T2",
			techlevel = 2,
			unitgroup = "buildert2",
			water_fall_damage_multiplier = 0,
			weapon1turretx = 200,
			weapon1turrety = 400,
		},
		featuredefs = {
			dead = {
				blocking = true,
				category = "corpses",
				collisionvolumeoffsets = "-0.042236328125 -0.00674871826172 -0.122863769531",
				collisionvolumescales = "37.7348022461 25.9745025635 40.3383178711",
				collisionvolumetype = "Box",
				damage = 1500,
				featuredead = "HEAP",
				footprintx = 3,
				footprintz = 3,
				height = 20,
				metal = 95,
				object = "Units/legmrv_dead.s3o",
				reclaimable = true,
			},
			heap = {
				blocking = false,
				category = "heaps",
				collisionvolumescales = "55.0 4.0 6.0",
				collisionvolumetype = "cylY",
				damage = 1000,
				footprintx = 3,
				footprintz = 3,
				height = 4,
				metal = 45,
				object = "Units/cor3X3C.s3o",
				reclaimable = true,
				resurrectable = 0,
			},
		},
		sfxtypes = {
			explosiongenerators = {
				[1] = "custom:barrelshot-tiny",
				[2] = "custom:dust_cloud_dirt_light",
			},
		},
		sounds = {
			build = "nanlath2",
			canceldestruct = "cancel2",
			capture = "capture2",
			repair = "repair2",
			underattack = "warning1",
			working = "reclaim1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "tcormove",
			},
			select = {
				[1] = "tcorsel",
			},
		},
		weapondefs = {
			quickshot_cannon = {
				accuracy = 7,
				areaofeffect = 16,
				avoidfeature = false,
				burst = 2,
				burstrate = 0.1,
				burnblow = false,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				duration = 0.03,
				edgeeffectiveness = 0.85,
				explosiongenerator = "custom:plasmahit-sparkonly",
				falloffrate = 0.2,
				firestarter = 0,
				impulsefactor = 0,
				intensity = 0.8,
				name = "Twin-barrel rapid-fire minigun",
				noselfdamage = true,
				ownerexpaccweight = 4.0,
				predictboost = 0.5,
				proximitypriority = 1,
				range = 240,
				reloadtime = 0.33,
				rgbcolor = "1 0.95 0.4",
				soundhit = "bimpact3",
				soundhitwet = "splshbig",
				soundstart = "mgun2",
				soundtrigger = true,
				sprayangle = 1000,
				texture1 = "shot",
				texture2 = "empty",
				thickness = 2.0,
				tolerance = 6000,
				turret = true,
				weapontype = "LaserCannon",
				weaponvelocity = 975,
				customparams = {
					turretspeedx = 300,
					turretspeedy = 300,
				},
				damage = {
					default = 30,
					vtol = 7.5,
				},
			},
		},
		weapons = {
			[1] = {
				burstcontrolwhenoutofarc = 2,
				def = "QUICKSHOT_CANNON",
				onlytargetcategory = "SURFACE",
			},
		},
	},
}
