-- cannon particles



local definitions = {
	
	["lightning_shard_trail"] = {
	sparks = {
		class = [[CSimpleParticleSystem]],
		count = 1,
		properties = {
			airdrag = 0.92,

			colormap = [[
				0.2 0.8 1 0.025
				0.1 0.5 1 0.012
				0 0 0 0.01
			]],

			directional = true,
			emitrot = 0,
			emitrotspread = 4,
			emitvector = [[dir]],
			gravity = [[0,0,0]],

			numparticles = 1,

			particlelife = 12,
			particlelifespread = 3,

			particlesize = 2.2,
			particlesizespread = .08,

			particlespeed = 0,
			particlespeedspread = 0,

			pos = [[0,0,0]],

			sizegrowth = -0.3,
			sizemod = 0.98,

			texture = [[spark]],

			useairlos = false,
		},
	},
},

	["cannonblaze-small"] = {
		flame = {
            air                = true,
            class              = [[CBitmapMuzzleFlame]],
            count              = 1,
            ground             = true,
            underwater         = true,
            water              = true,
            properties = {
                colormap           = [[0.9 0.65 0.3 0.01   0.9 0.6 0.2 0.01   0.9 0.3 0.1 0.01   0 0 0 0.01]],
                dir                = [[dir]],
                frontoffset        = 0,
                fronttexture       = [[none]],
                length             = [[-1.9 r0.2]],
                --pos                = [[-4, 0, 0]],
                sidetexture        = [[shot]],
                size               = 5.9,
                sizegrowth         = [[-0.2 r0.1]],
                ttl                = 1,
                useairlos          = true,
            },
        },
    	sparks = {
			air                = true,
			class              = [[CSimpleParticleSystem]],
			count              = 1,
			ground             = true,
			water              = true,
			underwater         = true,
			properties = {
				airdrag            = 0.85,
				colormap           = [[0.9 0.85 0.77 0.017   0.8 0.55 0.3 0.011   0 0 0 0]],
				directional        = true,
				emitrot            = 25,
				emitrotspread      = 30,
				emitvector         = [[0, 1, 0]],
				gravity            = [[0, -0.15, 0]],
				numparticles       = 1,
				particlelife       = 3,
				particlelifespread = 5,
				particlesize       = 13,
				particlesizespread = 10,
				particlespeed      = 1.2,
				particlespeedspread = 1.2,
				pos                = [[0, 0, 0]],
				sizegrowth         = 0.77,
				sizemod            = 0.8,
				texture            = [[gunshotglow]],
				useairlos          = true,
      		},
    	},
    	fireback = {
			air                = true,
			class              = [[CSimpleParticleSystem]],
			count              = 1,
			ground             = true,
			water              = true,
			underwater         = false,
			properties = {
		        airdrag            = 0.90,
		        colormap           = [[0.9 0.50 0.10 0.01   0.95 0.65 0.4 0.019   0.95 0.45 0.08 0.006   0.05 0.05 0.05 0.005    0 0 0 0]],
		        directional        = true,
		        emitrot            = 20,
		        emitrotspread      = 30,
		        emitvector         = [[0, 1, 0]],
		        gravity            = [[0, -0.15, 0]],
		        numparticles       = 1,
		        particlelife       = 3,
		        particlelifespread = 5,
		        particlesize       = 3.0,
		        particlesizespread = 0,
		        particlespeed      = 0.5,
		        particlespeedspread = 0.5,
		        pos                = [[-4, -1, 0]],
		        sizegrowth         = -0.8,
		        sizemod            = 1,
		        texture            = [[dirt]],
		        useairlos          = true,
	        },
	    },

	},
	["impulse-trail"] = {
		flame = {
            air                = true,
            class              = [[CBitmapMuzzleFlame]],
            count              = 1,
            ground             = true,
            underwater         = true,
            water              = true,
            properties = {
                colormap           = [[0.9 0.75 0.4 0.006   0.8 0.70 0.3 0.005   0.8 0.5 0.1 0.005   0 0 0 0.01]],
                dir                = [[dir]],
                frontoffset        = 0,
                fronttexture       = [[none]],
                length             = -2.8,
                sidetexture        = [[trail]],
                size               = 5.5,
                sizegrowth         = -0.09,
                ttl                = 3,
                useairlos          = true,
            },
        },
	},
	["gauss-trail"] = {
		coreglow = {
			class              = [[CSimpleParticleSystem]],
			count              = 1,
			properties = {
				airdrag            = 0.96,
				colormap           = [[
					1 0.86 0.95 0.18
					1 0.38 0.82 0.12
					0.34 0.28 1 0.07
					0 0 0 0.01
				]],
				directional        = true,
				emitrot            = 0,
				emitrotspread      = 3,
				emitvector         = [[dir]],
				gravity            = [[0,0,0]],
				numparticles       = 2,
				particlelife       = 5,
				particlelifespread = 2,
				particlesize       = 7.2,
				particlesizespread = 3.2,
				particlespeed      = 0,
				particlespeedspread = 0,
				pos                = [[0,0,0]],
				sizegrowth         = -0.18,
				sizemod            = 0.98,
				texture            = [[laserflare]],
				useairlos          = false,
			},
		},
		shockrings = {
			air                = true,
			class              = [[CBitmapMuzzleFlame]],
			count              = 1,
			ground             = true,
			underwater         = true,
			water              = true,
			properties = {
				colormap           = [[1 0.72 0.95 0.055   0.95 0.28 1 0.04   0.22 0.25 1 0.02   0 0 0 0.01]],
				dir                = [[dir]],
				frontoffset        = [[-4.0 r0.8]],
				fronttexture       = [[bubbletexture]],
				length             = [[0.45 r0.25]],
				sidetexture        = [[none]],
				size               = [[4.5 r2.3]],
				sizegrowth         = 0.75,
				ttl                = [[6.5 r2.5]],
				rotParams          = [[0, -70 r140, -35 r70]],
				useairlos          = true,
			},
		},
		taperrings = {
			air                = true,
			class              = [[CBitmapMuzzleFlame]],
			count              = 1,
			ground             = true,
			underwater         = true,
			water              = true,
			properties = {
				colormap           = [[0.85 0.55 1 0.035   0.45 0.42 1 0.028   0.14 0.16 0.55 0.014   0 0 0 0.01]],
				dir                = [[dir]],
				frontoffset        = [[-6.8 r1.0]],
				fronttexture       = [[bubbletexture]],
				length             = [[0.35 r0.2]],
				sidetexture        = [[none]],
				size               = [[2.4 r1.1]],
				sizegrowth         = -0.08,
				ttl                = [[5.5 r2]],
				rotParams          = [[0, -60 r120, -30 r60]],
				useairlos          = true,
			},
		},
		energywake = {
			air                = true,
			class              = [[CBitmapMuzzleFlame]],
			count              = 1,
			ground             = true,
			underwater         = true,
			water              = true,
			properties = {
				colormap           = [[1 0.8 0.95 0.016   1 0.34 0.86 0.024   0.2 0.28 1 0.014   0 0 0 0.01]],
				dir                = [[dir]],
				frontoffset        = [[-3.8 r0.8]],
				fronttexture       = [[none]],
				length             = [[-4.2 r1.2]],
				sidetexture        = [[trail]],
				size               = [[3.4 r1.0]],
				sizegrowth         = -0.26,
				ttl                = [[5 r2]],
				useairlos          = true,
			},
		},
		lightningarcs = {
			air                = true,
			class              = [[CBitmapMuzzleFlame]],
			count              = [[0 r1]],
			ground             = true,
			underwater         = true,
			water              = true,
			properties = {
				colormap           = [[1 0.82 0.95 0.055   1 0.34 0.9 0.05   0.28 0.3 1 0.028   0 0 0 0.01]],
				dir                = [[dir]],
				frontoffset        = [[-3.4 r0.8]],
				fronttexture       = [[none]],
				length             = [[-2.6 r1.2]],
				sidetexture        = [[lightning]],
				size               = [[5.0 r2.5]],
				sizegrowth         = -0.18,
				ttl                = [[3 r2]],
				rotParams          = [[0, -180 r360, -25 r50]],
				useairlos          = true,
			},
		},
		staticdischarges = {
			air                = true,
			class              = [[CBitmapMuzzleFlame]],
			count              = [[0 r2]],
			ground             = true,
			underwater         = true,
			water              = true,
			properties = {
				colormap           = [[1 0.86 1 0.07   1 0.28 0.95 0.055   0.25 0.28 1 0.035   0 0 0 0.01]],
				dir                = [[dir]],
				frontoffset        = [[-3.0 r2.2]],
				fronttexture       = [[none]],
				length             = [[-0.8 r2.2]],
				pos                = [[-7 r14, -7 r14, -7 r14]],
				sidetexture        = [[lightning]],
				size               = [[1.5 r5.5]],
				sizegrowth         = -0.35,
				ttl                = [[2 r3]],
				rotParams          = [[0, -180 r360, -180 r360]],
				useairlos          = true,
			},
		},
		sparks = {
			class              = [[CSimpleParticleSystem]],
			count              = 1,
			properties = {
				airdrag            = 0.92,
				colormap           = [[
					1 0.78 0.96 0.13
					1 0.32 0.85 0.1
					0.22 0.24 1 0.055
					0 0 0 0.01
				]],
				directional        = true,
				emitrot            = 0,
				emitrotspread      = 6,
				emitvector         = [[dir]],
				gravity            = [[0,0,0]],
				numparticles       = 3,
				particlelife       = 6,
				particlelifespread = 3,
				particlesize       = 3.2,
				particlesizespread = 1.8,
				particlespeed      = 0,
				particlespeedspread = 0,
				pos                = [[0,0,0]],
				sizegrowth         = -0.05,
				sizemod            = 0.99,
				texture            = [[laserflare]],
				useairlos          = false,
			},
		},
		snapsparks = {
			air                = true,
			class              = [[CSimpleParticleSystem]],
			count              = [[0 r2]],
			ground             = true,
			underwater         = true,
			water              = true,
			properties = {
				airdrag            = 0.82,
				colormap           = [[1 0.86 0.98 0.16   1 0.35 0.9 0.11   0.24 0.26 1 0.06   0 0 0 0.01]],
				directional        = true,
				emitrot            = 18,
				emitrotspread      = 42,
				emitvector         = [[dir]],
				gravity            = [[0,0,0]],
				numparticles       = [[1 r2]],
				particlelife       = 5,
				particlelifespread = 4,
				particlesize       = 2.2,
				particlesizespread = 2.6,
				particlespeed      = 0.35,
				particlespeedspread = 1.2,
				pos                = [[-2 r4, -2 r4, -2 r4]],
				sizegrowth         = -0.12,
				sizemod            = 0.92,
				texture            = [[sparkexplo]],
				useairlos          = false,
			},
		},
	},
	["gauss-trail-groundhit"] = {
		heatedgroundflash = {
			class              = [[CSimpleGroundFlash]],
			count              = 1,
			air                = true,
			ground             = true,
			unit               = false,
			nounit             = false,
			water              = false,
			underwater         = false,
			properties = {
				colormap           = [[0.42 0.55 1 0.16   0.1 0.18 1 0.08   0 0.03 0.35 0.025   0 0 0 0.01]],
				size               = [[5.6 r2.4]],
				sizegrowth         = -0.1,
				ttl                = [[12 r5]],
				texture            = [[groundflash]],
			},
		},
		groundarc = {
			air                = true,
			class              = [[CSimpleParticleSystem]],
			count              = 1,
			ground             = true,
			water              = false,
			underwater         = false,
			properties = {
				airdrag            = 0.86,
				colormap           = [[0.65 0.8 1 0.2   0.12 0.22 1 0.14   0.02 0.05 0.45 0.08   0 0 0 0.01]],
				directional        = true,
				emitrot            = 90,
				emitrotspread      = 55,
				emitvector         = [[0, 1, 0]],
				gravity            = [[0, 0, 0]],
				numparticles       = [[1 r1]],
				particlelife       = 4,
				particlelifespread = 4,
				particlesize       = 3.92,
				particlesizespread = 4.48,
				particlespeed      = 0.4,
				particlespeedspread = 1.4,
				pos                = [[-1 r2, 1, -1 r2]],
				sizegrowth         = -0.35,
				sizemod            = 0.88,
				texture            = [[lightning]],
				useairlos          = false,
			},
		},
		groundscar = {
			air                = true,
			class              = [[CExpGenSpawner]],
			count              = 1,
			ground             = true,
			water              = true,
			underwater         = true,
			properties = {
				delay              = 0,
				explosiongenerator = [[custom:gauss-trail-groundscar]],
				pos                = [[0, 0, 0]],
			},
		},
		sparks = {
			air                = true,
			class              = [[CSimpleParticleSystem]],
			count              = 1,
			ground             = true,
			water              = false,
			underwater         = false,
			properties = {
				airdrag            = 0.9,
				colormap           = [[0.55 0.7 1 0.04   0.12 0.22 1 0.03   0.02 0.05 0.45 0.018   0 0 0 0.01]],
				directional        = true,
				emitrot            = 90,
				emitrotspread      = 25,
				emitvector         = [[0, 1, 0]],
				gravity            = [[0, -0.05, 0]],
				numparticles       = [[1 r1]],
				particlelife       = 5,
				particlelifespread = 4,
				particlesize       = 3.92,
				particlesizespread = 3.36,
				particlespeed      = 0.35,
				particlespeedspread = 0.8,
				pos                = [[0, 1, 0]],
				sizegrowth         = 0.25,
				sizemod            = 0.75,
				texture            = [[gunshotglow]],
				useairlos          = false,
			},
		},
	},
	["gauss-trail-groundscar"] = {
		heatedgroundflash = {
			class              = [[CSimpleGroundFlash]],
			count              = 1,
			air                = false,
			ground             = true,
			unit               = false,
			nounit             = false,
			water              = false,
			underwater         = false,
			properties = {
				colormap           = [[1 0.15 0.05 0.4   0 0 0 0.01]],
				size               = 3,
				sizegrowth         = 0,
				texture            = [[groundflash]],
				ttl                = 33,
			},
		},
	},
	["arty-fast"] = {
		flame = {
            air                = true,
            class              = [[CBitmapMuzzleFlame]],
            count              = 1,
            ground             = true,
            underwater         = true,
            water              = true,
            properties = {
                colormap           = [[0.9 0.75 0.3 0.0   0.9 0.75 0.3 0.009   0.9 0.7 0.2 0.007   0.9 0.3 0.1 0.004   0 0 0 0.01]],
                dir                = [[dir]],
                frontoffset        = 0,
                fronttexture       = [[none]],
                length             = -3.8,
                sidetexture        = [[trail]],
                size               = 1.8,
                sizegrowth         = -0.05,
                ttl                = 5,
                useairlos          = true,
            },
        },
	},
	["Heavy-Plasma"] = {
		flame = {
            air                = true,
            class              = [[CBitmapMuzzleFlame]],
            count              = 1,
            ground             = true,
            underwater         = true,
            water              = true,
            properties = {
                colormap           = [[0.9 0.65 0.3 0.0   0.9 0.65 0.3 0.007   0.9 0.6 0.2 0.006   0.8 0.3 0.1 0.004   0 0 0 0.01]],
                dir                = [[dir]],
                frontoffset        = 0, --0.03
                fronttexture       = [[null]], --glow
                length             = -1.5,
                sidetexture        = [[trail]],
                size               = 14,
                sizegrowth         = 0.0,
                ttl                = 3,
                useairlos          = true,
                castShadow         = true,
        	},
    	},
	},
	["arty-small"] = {
		flame = {
            air                = true,
            class              = [[CBitmapMuzzleFlame]],
            count              = 1,
            ground             = true,
            underwater         = true,
            water              = true,
            properties = {
                colormap           = [[0.9 0.75 0.4 0.0  0.9 0.75 0.4 0.00.9 0.75 0.4 0.006   0.8 0.70 0.3 0.005   0.8 0.5 0.1 0.005   0 0 0 0.01]],
                dir                = [[dir]],
                frontoffset        = 0,
                fronttexture       = [[none]],
                length             = -3.9,
                sidetexture        = [[trail]],
                size               = 2.5,
                sizegrowth         = -0.16,
                ttl                = 3,
                useairlos          = true,
            },
        },
	},
    ["arty-medium"] = {
		flame = {
            air                = true,
            class              = [[CBitmapMuzzleFlame]],
            count              = 1,
            ground             = true,
            underwater         = true,
            water              = true,
            properties = {
                colormap           = [[0.9 0.65 0.3 0   0.9 0.65 0.3 0.006   0.9 0.6 0.2 0.005   0.8 0.3 0.1 0.004   0 0 0 0.01]],
                dir                = [[dir]],
                frontoffset        = 0,
                fronttexture       = [[trans]],
                length             = -4.2,
                sidetexture        = [[trail]],
                size               = 4.2,
                sizegrowth         = -0.09,
                ttl                = 4,
                useairlos          = true,
                castShadow         = true,
        	},
    	},
	},
	["arty-large"] = {
		flame = {
            air                = true,
            class              = [[CBitmapMuzzleFlame]],
            count              = 1,
            ground             = true,
            underwater         = true,
            water              = true,
            properties = {
                colormap           = [[0.9 0.65 0.3 0.0   0.9 0.65 0.3 0.007   0.9 0.6 0.2 0.006   0.8 0.3 0.1 0.004   0 0 0 0.01]],
                dir                = [[dir]],
                frontoffset        = 0, --0.03
                fronttexture       = [[null]], --glow
                length             = -4.9,
                sidetexture        = [[trail]],
                size               = 5.5,
                sizegrowth         = -0.09,
                ttl                = 4,
                useairlos          = true,
                castShadow         = true,
        	},
    	},
	},
	["arty-heavy"] = {
		flame = {
            air                = true,
            class              = [[CBitmapMuzzleFlame]],
            count              = 1,
            ground             = true,
            underwater         = true,
            water              = true,
            properties = {
                colormap           = [[0.9 0.65 0.3 0.0   0.9 0.65 0.3 0.007   0.9 0.6 0.2 0.006   0.9 0.3 0.1 0.005   0 0 0 0.01]],
                dir                = [[dir]],
                frontoffset        = 0, --0.05
                fronttexture       = [[null]], --glow
                length             = -5.5,
                sidetexture        = [[trail]],
                size               = 7.2,
                sizegrowth         = -0.09,
                ttl                = 4,
                useairlos          = true,
                castShadow         = true,
            },
        },

        sparks = {
			air                = true,
			class              = [[CSimpleParticleSystem]],
			count              = 0,
			ground             = true,
			water              = true,
			underwater         = true,
			properties = {
				airdrag            = 0.85,
				colormap           = [[0.9 0.85 0.77 0.017   0.8 0.55 0.3 0.011   0 0 0 0]],
				directional        = true,
				emitrot            = 25,
				emitrotspread      = 30,
				emitvector         = [[0, 1, 0]],
				gravity            = [[0, -0.15, 0]],
				numparticles       = 2,
				particlelife       = 3,
				particlelifespread = 3,
				particlesize       = 14,
				particlesizespread = 18,
				particlespeed      = 1.1,
				particlespeedspread = 1.5,
				pos                = [[0, 0, 0]],
				sizegrowth         = -0.3,
				sizemod            = 0.7,
				texture            = [[gunshotglow]],
				useairlos          = true,
      		},
    	},
	},
	["arty-extraheavy"] = {
		flame = {
            air                = true,
            class              = [[CBitmapMuzzleFlame]],
            count              = 1,
            ground             = true,
            underwater         = true,
            water              = true,
            properties = {
                colormap           = [[0.9 0.65 0.3 0.01   0.9 0.6 0.2 0.01   0.9 0.3 0.1 0.008   0 0 0 0.01]],
                dir                = [[dir]],
                frontoffset        = 0, --0.05
                fronttexture       = [[null]], --glow
                length             = -5.8,
                sidetexture        = [[trail]],
                size               = 17,
                sizegrowth         = -0.20,
                ttl                = 2,
                useairlos          = true,
                castShadow         = true,
            },
        },

        sparks = {
			air                = true,
			class              = [[CSimpleParticleSystem]],
			count              = 0,
			ground             = true,
			water              = true,
			underwater         = true,
			properties = {
				airdrag            = 0.85,
				colormap           = [[0.9 0.85 0.77 0.017   0.8 0.55 0.3 0.011   0 0 0 0]],
				directional        = true,
				emitrot            = 25,
				emitrotspread      = 30,
				emitvector         = [[0, 1, 0]],
				gravity            = [[0, -0.15, 0]],
				numparticles       = 2,
				particlelife       = 3,
				particlelifespread = 3,
				particlesize       = 14,
				particlesizespread = 18,
				particlespeed      = 1.1,
				particlespeedspread = 1.5,
				pos                = [[0, 0, 0]],
				sizegrowth         = -0.3,
				sizemod            = 0.7,
				texture            = [[gunshotglow]],
				useairlos          = true,
      		},
    	},
	},
	["arty-huge"] = {
		flame = {
            air                = true,
            class              = [[CBitmapMuzzleFlame]],
            count              = 1,
            ground             = true,
            underwater         = true,
            water              = true,
            properties = {
                colormap           = [[0.9 0.65 0.3 0.01   0.9 0.6 0.2 0.01   0.9 0.3 0.1 0.01   0 0 0 0.01]],
                dir                = [[dir]],
                frontoffset        = 0, --0.04
                fronttexture       = [[null]], --was glow before
                length             = -6,
                sidetexture        = [[shot]],
                size               = 20.2,
                sizegrowth         = -0.20,
                ttl                = 2,
                --rotParams          = [[0 , 0, -180 r360]],
                useairlos          = true,
                castShadow         = true,
            },
        },
        sparks = {
			air                = true,
			class              = [[CSimpleParticleSystem]],
			count              = 0,
			ground             = true,
			water              = true,
			underwater         = true,
			properties = {
				airdrag            = 0.87,
				colormap           = [[0.9 0.85 0.77 0.017   0.8 0.55 0.3 0.011   0 0 0 0]],
				directional        = true,
				emitrot            = 25,
				emitrotspread      = 30,
				emitvector         = [[0, 1, 0]],
				gravity            = [[0, -0.15, 0]],
				numparticles       = 2,
				particlelife       = 3,
				particlelifespread = 4,
				particlesize       = 26,
				particlesizespread = 26,
				particlespeed      = 1.5,
				particlespeedspread = 2.0,
				pos                = [[0, 0, 0]],
				sizegrowth         = -0.3,
				sizemod            = 0.8,
				texture            = [[gunshotglow]],
				useairlos          = true,
				castShadow         = true,
      		},
    	},
	},
	["arty-botrail"] = {
		fireglow = {
        air                = true,
        class              = [[CSimpleParticleSystem]],
        count              = 1,
        ground             = true,
        water              = true,
        properties = {
            airdrag            = 1,
            colormap           = [[0.44 0.48 1 0.2   0 0 0 0.01]],
            directional        = true,
            emitrot            = -180,
            emitrotspread      = 0,
            emitvector         = [[dir]],
            gravity            = [[0.0, 0.0, 0.0]],
            numparticles       = 1,
            particlelife       = 4,
            particlelifespread = 0,
            particlesize       = 35,
            particlesizespread = 10,
            particlespeed      = 0,
            particlespeedspread = 0,
            pos                = [[0.0, 0, 0.0]],
            sizegrowth         = -5,
            sizemod            = 1,
            texture            = [[glow]],
            useairlos          = true,
        },
    },
		flame = {
            air                = true,
            class              = [[CBitmapMuzzleFlame]],
            count              = 1,
            ground             = true,
            underwater         = true,
            water              = true,
            properties = {
                colormap           = [[0.49 0.49 0.9 0.01   0.44 0.44 0.9 0.01   0.35 0.35 0.88 0.01   0 0 0 0.01]],
                dir                = [[dir]],
                frontoffset        = 0.1,
                fronttexture       = [[blastwave]],
                length             = -5.8,
                sidetexture        = [[shot]],
                size               = 5.2,
                sizegrowth         = -0.15,
                ttl                = 9,
                useairlos          = true,
            },
        },
      sparks = {
			air                = true,
			class              = [[CSimpleParticleSystem]],
			count              = 0,
			ground             = true,
			water              = true,
			underwater         = true,
			properties = {
				airdrag            = 0.87,
				colormap           = [[0.5 0.52 1 0.017   0.3 0.3 0.8 0.011   0 0 0 0]],
				directional        = true,
				emitrot            = 25,
				emitrotspread      = 30,
				emitvector         = [[0, 1, 0]],
				gravity            = [[0, -0.15, 0]],
				numparticles       = 2,
				particlelife       = 3,
				particlelifespread = 4,
				particlesize       = 30,
				particlesizespread = 30,
				particlespeed      = 1.5,
				particlespeedspread = 2.0,
				pos                = [[0, 0, 0]],
				sizegrowth         = -0.3,
				sizemod            = 0.8,
				texture            = [[gunshotglow]],
				useairlos          = true,
      		},
    	},
	},
	["railgun"] = {
         shockwaves = {
            air                = true,
            class              = [[CBitmapMuzzleFlame]],
            count              = 1,
            ground             = true,
            underwater         = true,
            water              = true,
            properties = {
                colormap           = [[0.67 0.48 1 0.01   0.27 0.58 0.89 0.03   0.15 0.19 0.35 0.01   0 0 0 0.01]],
                dir                = [[dir]],
                frontoffset        = [[0.4 r0.2]],
                fronttexture       = [[bubbletexture]],
                length             = [[0.9 r0.6]],
                sidetexture        = [[longshot]],
                size               = [[5 r4.1]],
                sizegrowth         = 0.65,
                ttl                = [[18 r6]],
                useairlos          = true,
            },
        },
        sparks = {
			air                = true,
			class              = [[CSimpleParticleSystem]],
			count              = 0,
			ground             = true,
			water              = true,
			underwater         = true,
			properties = {
				airdrag            = 0.87,
				colormap           = [[0.67 0.82 0 0.01   0.27 0.58 0.89 0.01   0 0 0 0]],
				directional        = true,
				emitrot            = 25,
				emitrotspread      = 30,
				emitvector         = [[0, 1, 0]],
				gravity            = [[0, -0.15, 0]],
				numparticles       = 1,
				particlelife       = 10,
				particlelifespread = 15,
				particlesize       = 30,
				particlesizespread = 30,
				particlespeed      = 1.5,
				particlespeedspread = 2.0,
				pos                = [[0, 0, 0]],
				sizegrowth         = -0.3,
				sizemod            = 0.8,
				texture            = [[gunshotglow]],
				useairlos          = true,
      		},
    	},
	},
	["railgun-old"] = {
         lightningtrail = {
       air                = true,
       class              = [[CSimpleParticleSystem]],
       count              = 1,
       ground             = true,
       underwater         = true,
       water              = true,
       properties = {
         airdrag            = 0.89,
         colormap           = [[0 0 0 0   0 0 0 0    1 0.85 0.6 0.22  1 0.63 0.3 0.12  0.54 0.52 0.4 0.06   0 0 0 0.01]],
         directional        = true,
         emitrot            = 45,
         emitrotspread      = 32,
         emitvector         = [[0.5, 1, 0.5]],
         gravity            = [[0, -0.05, 0]],
         numparticles       = 1,
         particlelife       = 5,
         particlelifespread = 30,
         particlesize       = 1,
         particlesizespread = 10,
         particlespeed      = 1,
         particlespeedspread = 2,
         pos                = [[0, 0, 0]],
         sizegrowth         = 3,
         sizemod            = 0.90,
         texture            = [[lightning]],
       },
     },
        sparks = {
			air                = true,
			class              = [[CSimpleParticleSystem]],
			count              = 1,
			ground             = true,
			water              = true,
			underwater         = true,
			properties = {
				airdrag            = 0.87,
				colormap           = [[0.9 0.85 0.77 0.017   0.8 0.55 0.3 0.011   0 0 0 0]],
				directional        = true,
				emitrot            = 25,
				emitrotspread      = 30,
				emitvector         = [[0, 1, 0]],
				gravity            = [[0, -0.15, 0]],
				numparticles       = 2,
				particlelife       = 3,
				particlelifespread = 4,
				particlesize       = 30,
				particlesizespread = 30,
				particlespeed      = 1.5,
				particlespeedspread = 2.0,
				pos                = [[0, 0, 0]],
				sizegrowth         = -0.3,
				sizemod            = 0.8,
				texture            = [[gunshotglow]],
				useairlos          = true,
      		},
    	},
	},


	["starfire"] = {
		flame = {
            air                = true,
            class              = [[CBitmapMuzzleFlame]],
            count              = 1,
            ground             = true,
            underwater         = true,
            water              = true,
            properties = {
                colormap           = [[0.6 0.6 1 0.04   0.65 0.65 1 0.02   0.3 0.4 0.8 0.01   0 0 0 0.01]],
                dir                = [[dir]],
                frontoffset        = 0, --0.04
                fronttexture       = [[glow]], --glow
                length             = -18,
                sidetexture        = [[shot-trail]],
                size               = 9.2,
                sizegrowth         = -0.16,
                ttl                = 3,
                --rotParams          = [[0 , 0, -180 r360]],
                useairlos          = true,
                castShadow         = true,
            },
        },
        sparks = {
			air                = true,
			class              = [[CSimpleParticleSystem]],
			count              = 1,
			ground             = true,
			water              = true,
			underwater         = true,
			properties = {
				airdrag            = 0.67,
				colormap           = [[0.9 0.95 0.97 0.017   0.6 0.65 0.9 0.011   0 0 0 0]],
				directional        = false,
				emitrot            = 25,
				emitrotspread      = 30,
				emitvector         = [[0, 1, 0]],
				gravity            = [[0, -0.15, 0]],
				numparticles       = [[0.55 r0.7]],
				particlelife       = 4,
				particlelifespread = 5,
				particlesize       = 7,
				particlesizespread = 14,
				particlespeed      = 1.5,
				particlespeedspread = 2.0,
				pos                = [[0, 0, 0]],
				rotParams          = [[-20 r40, -5 r10, -180 r360]],
				sizegrowth         = 1.7,
				sizemod            = 0.9,
				texture            = [[gunshotxl]],
				useairlos          = true,
				castShadow         = true,
      		},
    	},
	},
	["starfire-small"] = {
		flame = {
            air                = true,
            class              = [[CBitmapMuzzleFlame]],
            count              = 1,
            ground             = true,
            underwater         = true,
            water              = true,
            properties = {
                colormap           = [[0.3 0.45 1 0.01   0.5 0.5 1 0.01   0.7 0.7 1 0.01   0 0 0 0.01]],
                dir                = [[dir]],
                frontoffset        = 0, --0.04
                fronttexture       = [[glow]], --glow
                length             = -9,
                sidetexture        = [[shot-trail]],
                size               = 7,
                sizegrowth         = -0.18,
                ttl                = 3,
                --rotParams          = [[0 , 0, -180 r360]],
                useairlos          = true,
                castShadow         = true,
            },
        },
        sparks = {
			air                = true,
			class              = [[CSimpleParticleSystem]],
			count              = 1,
			ground             = true,
			water              = true,
			underwater         = true,
			properties = {
				airdrag            = 0.7,
				colormap           = [[0.9 0.95 0.97 0.017   0.6 0.65 0.7 0.017   0 0 0 0]],
				directional        = false,
				emitrot            = 25,
				emitrotspread      = 30,
				emitvector         = [[0, 0, 0]],
				gravity            = [[0, -0.06, 0]],
				numparticles       = 1, --[[0.6 r0.75]]
				particlelife       = 5,
				particlelifespread = 0,
				particlesize       = 18,
				particlesizespread = 5,
				particlespeed      = 0,
				particlespeedspread = 0,
				pos                = [[0, 0, 0]],
				sizegrowth         = -2.8,
				sizemod            = 1,
				texture            = [[bubbletexture]],
				useairlos          = true,
				--castShadow         = true,
      		},
    	},
        -- sparks-old = {
		-- 	air                = true,
		-- 	class              = [[CSimpleParticleSystem]],
		-- 	count              = 1,
		-- 	ground             = true,
		-- 	water              = true,
		-- 	underwater         = true,
		-- 	properties = {
		-- 		airdrag            = 0.67,
		-- 		colormap           = [[0.9 0.95 0.97 0.017   0.6 0.65 0.9 0.011   0 0 0 0]],
		-- 		directional        = true,
		-- 		emitrot            = 25,
		-- 		emitrotspread      = 30,
		-- 		emitvector         = [[0, 1, 0]],
		-- 		gravity            = [[0, -0.15, 0]],
		-- 		numparticles       = 2,
		-- 		particlelife       = 3,
		-- 		particlelifespread = 4,
		-- 		particlesize       = 30,
		-- 		particlesizespread = 20,
		-- 		particlespeed      = 1.5,
		-- 		particlespeedspread = 2.0,
		-- 		pos                = [[0, 0, 0]],
		-- 		sizegrowth         = 1,
		-- 		sizemod            = 0.8,
		-- 		texture            = [[gunshotglow]],
		-- 		useairlos          = true,
		-- 		castShadow         = true,
      	-- 	},
    	-- },
	},

	  ["starfire_tiny"] = {
		flame = {
            air                = true,
            class              = [[CBitmapMuzzleFlame]],
            count              = 1,
            ground             = true,
            underwater         = true,
            water              = true,
            properties = {
                colormap           = [[0.35 0.45 0.45 0.015   0.5 0.5 0.5 0.015   0.7 0.7 0.7 0.015   0 0 0 0.015]],
                dir                = [[dir]],
                frontoffset        = 0, --0.04
                fronttexture       = [[glow]], --glow
                length             = -6,
                sidetexture        = [[shot-trail]],
                size               = 6,
                sizegrowth         = -0.06,
                ttl                = 2,
                --rotParams          = [[0 , 0, -180 r360]],
                useairlos          = true,
                castShadow         = true,
            },
        },
        sparks = {
			air                = true,
			class              = [[CSimpleParticleSystem]],
			count              = 1,
			ground             = true,
			water              = true,
			underwater         = true,
			properties = {
				airdrag            = 0.7,
				colormap           = [[0.9 0.95 0.97 0.017   0.6 0.65 0.7 0.017   0 0 0 0]],
				directional        = false,
				emitrot            = 20,
				emitrotspread      = 25,
				emitvector         = [[0, 0, 0]],
				gravity            = [[0, -0.06, 0]],
				numparticles       = 1, --[[0.6 r0.75]]
				particlelife       = 3,
				particlelifespread = 0,
				particlesize       = 6,
				particlesizespread = 0,
				particlespeed      = 0,
				particlespeedspread = 0,
				pos                = [[0, 0, 0]],
				sizegrowth         = -0.2,
				sizemod            = 1,
				texture            = [[bubbletexture]],
				useairlos          = true,
				--castShadow         = true,
      		},
    	},
	},

	["ministarfire"] = {
		flame = {
            air                = true,
            class              = [[CBitmapMuzzleFlame]],
            count              = 1,
            ground             = true,
            underwater         = true,
            water              = true,
            properties = {
                colormap           = [[0.35 0.45 0.45 0.015   0.5 0.5 0.5 0.015   0.7 0.7 0.7 0.015   0 0 0 0.015]],
                dir                = [[dir]],
                frontoffset        = 0, --0.04
                fronttexture       = [[glow]], --glow
                length             = -10,
                sidetexture        = [[shot-trail]],
                size               = 2.2,
                sizegrowth         = -0.18,
                ttl                = 2,
                --rotParams          = [[0 , 0, -180 r360]],
                useairlos          = true,
                castShadow         = true,
            },
        },
        sparks = {
			air                = true,
			class              = [[CSimpleParticleSystem]],
			count              = 1,
			ground             = true,
			water              = true,
			underwater         = true,
			properties = {
				airdrag            = 0.67,
				colormap           = [[0.9 0.95 0.97 0.017   0.6 0.65 0.7 0.017   0 0 0 0]],
				directional        = false,
				emitrot            = 25,
				emitrotspread      = 30,
				emitvector         = [[0, 1, 0]],
				gravity            = [[0, -0.15, 0]],
				numparticles       = 1,
				particlelife       = 2,
				particlelifespread = 0,
				particlesize       = 7,
				particlesizespread = 0,
				particlespeed      = 0,
				particlespeedspread = 0,
				pos                = [[0, 0, 0]],
				--rotParams          = [[-5 r10, -5 r10, 0]],
				sizegrowth         = -1.9,
				sizemod            = 1,
				texture            = [[bubbletexture]],
				useairlos          = true,
				--castShadow         = true,
      		},
    	},
	},
  ["starfire_arty"] = {
		flame = {
            air                = true,
            class              = [[CBitmapMuzzleFlame]],
            count              = 1,
            ground             = true,
            underwater         = true,
            water              = true,
            properties = {
                colormap           = [[0.35 0.45 0.45 0.015   0.5 0.5 0.5 0.015   0.7 0.7 0.7 0.015   0 0 0 0.015]],
                dir                = [[dir]],
                frontoffset        = 0, --0.04
                fronttexture       = [[glow]], --glow
                length             = -8,
                sidetexture        = [[shot-trail]],
                size               = 8.2,
                sizegrowth         = -0.06,
                ttl                = 2,
                --rotParams          = [[0 , 0, -180 r360]],
                useairlos          = true,
                castShadow         = true,
            },
        },
        sparks = {
			air                = true,
			class              = [[CSimpleParticleSystem]],
			count              = 1,
			ground             = true,
			water              = true,
			underwater         = true,
			properties = {
				airdrag            = 0.7,
				colormap           = [[0.9 0.95 0.97 0.017   0.6 0.65 0.7 0.017   0 0 0 0]],
				directional        = false,
				emitrot            = 25,
				emitrotspread      = 30,
				emitvector         = [[0, 0, 0]],
				gravity            = [[0, -0.06, 0]],
				numparticles       = 1, --[[0.6 r0.75]]
				particlelife       = 4,
				particlelifespread = 0,
				particlesize       = 10,
				particlesizespread = 0,
				particlespeed      = 0,
				particlespeedspread = 0,
				pos                = [[0, 0, 0]],
				sizegrowth         = -0.2,
				sizemod            = 1,
				texture            = [[bubbletexture]],
				useairlos          = true,
				--castShadow         = true,
      		},
    	},
	},
}

-- add purple scavenger variants
local scavengerDefs = {}
for k,v in pairs(definitions) do
  scavengerDefs[k..'-purple'] = table.copy(definitions[k])
end

local purpleEffects = {
  flame = {
    properties = {
      colormap           = [[0.8 0.5 1 0.01   0.65 0.2 0.9 0.01   0.35 0.07 0.6 0.01   0 0 0 0.01]],
    },
  },
  -- fireback = {
  --   properties = {
  --     colormap           = [[0.8 0.45 1 0.01   0.8 0.45 1 0.019   0.65 0.2 0.9 0.006   0.05 0.05 0.05 0.005    0 0 0 0]],
  --   },
  -- },
  -- traillight = {
  --   properties = {
  --     colormap           = [[0.8 0.45 1 0.01   0.8 0.45 1 0.019   0.65 0.2 0.9 0.006   0.05 0.05 0.05 0.005    0 0 0 0]],
  --   },
  -- },
}
for defName, def in pairs(scavengerDefs) do
  for effect, effectParams in pairs(purpleEffects) do
    if scavengerDefs[defName][effect] then
      for param, paramValue in pairs(effectParams) do
        if scavengerDefs[defName][effect][param] then
          if param == 'properties' then
            for property,propertyValue in pairs(paramValue) do
              if scavengerDefs[defName][effect][param][property] then
                scavengerDefs[defName][effect][param][property] = propertyValue
              end
            end
          else
            scavengerDefs[defName][effect][param] = paramValue
          end
        end
      end
    end
  end
end

table.mergeInPlace(definitions, scavengerDefs)

return definitions
