local function BlueTrail(vaporLife, vaporSpread, glowLife, glowSpread, sizeScale)
	return {
		vapor = {
			air = true,
			class = [[CSimpleParticleSystem]],
			count = 1,
			ground = true,
			water = true,
			properties = {
				airdrag = 0.94,
				colormap = [[1 1 1 0.78   0.42 0.78 1 0.68   0.12 0.42 1 0.38   0.02 0.12 0.5 0.10   0 0 0 0]],
				directional = false,
				emitrot = 0,
				emitrotspread = 8,
				emitvector = [[0, 1, 0]],
				gravity = [[0, 0.015, 0]],
				numparticles = 1,
				particlelife = vaporLife,
				particlelifespread = vaporSpread,
				particlesize = 2.3 * sizeScale,
				particlesizespread = 0.7 * sizeScale,
				particlespeed = 0.08,
				particlespeedspread = 0.12,
				pos = [[-0.2 r0.4, -0.2 r0.4, -0.2 r0.4]],
				sizegrowth = 0.18,
				sizemod = 0.98,
				texture = [[smoke_puff2]],
				useairlos = true,
			},
		},
		glow = {
			air = true,
			class = [[CSimpleParticleSystem]],
			count = 1,
			ground = true,
			water = true,
			properties = {
				airdrag = 1,
				colormap = [[1 1 1 0.90   0.25 0.7 1 0.72   0.04 0.28 1 0.34   0 0.08 0.4 0.06   0 0 0 0]],
				directional = false,
				emitrot = 0,
				emitrotspread = 0,
				emitvector = [[0, 1, 0]],
				gravity = [[0, 0, 0]],
				numparticles = 1,
				particlelife = glowLife,
				particlelifespread = glowSpread,
				particlesize = 1.5 * sizeScale,
				particlesizespread = 0.35 * sizeScale,
				particlespeed = 0,
				particlespeedspread = 0,
				pos = [[0, 0, 0]],
				sizegrowth = 0.08,
				sizemod = 0.97,
				texture = [[glow2]],
				useairlos = true,
			},
		},
	}
end

return {
	["paradrop-blue-trail-short"] = BlueTrail(6, 2, 3, 1, 0.85),
	["paradrop-blue-trail-medium"] = BlueTrail(9, 2, 5, 1, 0.925),
	["paradrop-blue-trail-long"] = BlueTrail(14, 3, 7, 2, 1),
}
