return {
	corsfig2 = {
		blocking = false,
		buildpic = "CORSFIG2.DDS",
		buildtime = 18000,
		canfly = true,
		canmove = true,
		collide = true,
		cruisealtitude = 90,
		energycost = 8200,
		explodeas = "mediumexplosiongeneric",
		footprintx = 4,
		footprintz = 4,
		health = 1960,
		maxacc = 0.1325,
		maxaileron = 0.01347,
		maxbank = 0.8,
		maxdec = 0.0725,
		maxelevator = 0.00972,
		maxpitch = 0.625,
		maxrudder = 0.00522,
		maxslope = 10,
		maxwaterdepth = 0,
		metalcost = 410,
		nochasecategory = "VTOL",
		objectname = "Units/CORSFIG2.s3o",
		script = "Units/CORSFIG2.cob",
		seismicsignature = 0,
		selfdestructas = "mediumExplosionGenericSelfd",
		sightdistance = 500,
		speed = 279,
		speedtofront = 0.063,
		turnradius = 64,
		usesmoothmesh = true,
		wingangle = 0.06222,
		wingdrag = 0.18,
		customparams = {
			model_author = "Beherith",
			normaltex = "unittextures/cor_normal.dds",
			subfolder = "CorAircraft/T2",
			techlevel = 2,
			unitgroup = "weapon",
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "vtolcrmv",
			},
			select = {
				[1] = "vtolcrac",
			},
		},
		weapondefs = {
			banisher = {
				areaofeffect = 128,
				avoidfeature = false,
				cegtag = "missiletraillarge-red",
				craterareaofeffect = 128,
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0.55,
				explosiongenerator = "custom:genericshellexplosion-large-bomb",
				firestarter = 20,
				flighttime = 2.7,
				impulsefactor = 0.9,
				model = "banishermissile.s3o",
				name = "Banisher",
				noselfdamage = true,
				range = 800,
				reloadtime = 2.5,
				smokecolor = 0.82,
				smokeperiod = 7,
				smokesize = 11.3,
				smoketime = 48,
				smoketrail = true,
				smoketrailcastshadow = false,
				soundhit = "corban_b",
				soundhitwet = "splsmed",
				soundstart = "corban_a",
				startvelocity = 240,
				texture1 = "null",
				texture2 = "railguntrail",
				tolerance = 5000,
				tracks = true,
				trajectoryheight = 0.45,
				turnrate = 12000,
				turret = true,
				weaponacceleration = 180,
				weapontimer = 5,
				weapontype = "MissileLauncher",
				weaponvelocity = 720,
				customparams = {
					projectile_destruction_method = "descend",
					overrange_distance = 920,
				},
				damage = {
					default = 400,
					subs = 200,
				},
			},
			wing_laser = {
				areaofeffect = 14,
				avoidfeature = false,
				beamtime = 0.15,
				burst = 2,
				burstrate = 0.1,
				corethickness = 0.25,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0.15,
				energypershot = 75,
				explosiongenerator = "custom:laserhit-medium-green",
				firestarter = 90,
				impactonly = 1,
				impulsefactor = 0,
				laserflaresize = 9.9,
				name = "Fixed-wing heavy high energy laser",
				noselfdamage = true,
				range = 620,
				reloadtime = 1.8,
				rgbcolor = "0 1 0",
				soundhitdry = "",
				soundhitwet = "sizzle",
				soundstart = "Lasrmas2",
				soundtrigger = 1,
				thickness = 3,
				tolerance = 2000,
				turret = false,
				weapontype = "BeamLaser",
				weaponvelocity = 2250,
				damage = {
					commanders = 580.5,
					default = 387,
					vtol = 35,
				},
			},
		},
		weapons = {
			[1] = {
				def = "BANISHER",
				onlytargetcategory = "SURFACE",
			},
			[2] = {
				badtargetcategory = "VTOL",
				def = "WING_LASER",
				maindir = "0 0 1",
				maxangledif = 90,
				onlytargetcategory = "NOTSUB",
			},
		},
	},
}
